### ISSUE TITLE
Question about the comparison approaches

### ISSUE THREAD

**Issue by BayanHashr** [zhlu007/GoCC#1]
Dear Mr.Zhlu
I'm citing GoCC paper in my paper, and I want to know how do you compare your work with MCT-M and MCT-S approaches.
I can't find it in the code 
thank you 
my best regards

**Comment by zhlu007** [comment]
Hi,&nbsp;


Thank you for your interest in our works.&nbsp;
As your concern, for the codes of MCT-M and MCT-S, you may need to ask the original authors for them.


Good luck and Best regards,


Lu&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Jan 13, 2022 07:53 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[zhlu007/GoCC] Question about the comparison approaches (Issue #1)

&nbsp;



 
Dear Mr.Zhlu
 I'm citing GoCC paper in my paper, and I want to know how do you compare your work with MCT-M and MCT-S approaches.
 I can't find it in the code
 thank you
 my best regards
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
